---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
securityDefinitions:
  JWT:
    description: the jwt for API auth
    type: apiKey
    name: Authorization
    in: header
